### ISSUE TITLE
Incorrect bucket prefix for Amazoni-1 assets.

### ISSUE THREAD

**Issue by sharkinsspatial** [stactools-packages/amazonia-1#12]
**Describe the bug**
The package currently produces assets with the bucket prefix `s3://cbers-pds` rather than the actual `s3://amazonia-pds` where the assets exist.

**To reproduce**
Run the current tests which demonstrate that items have assets using the [cbers-pds prefix](https://github.com/stactools-packages/amazonia-1/blob/d2ac0c79e2af1986a5096d2a64d96a1c96d92c9c/src/stactools/amazonia_1/stac.py#L487).

**Expected behavior**
Assets are produced using the same prefix as the xml parameter path.

**Comment by fredliporace** [comment]
@sharkinsspatial are you able to test ASDI integration from a github branch or do you need a new version to be available in PyPI? This is a quick fix but I'd like to run more extensive tests before publishing a new version.

**Comment by sharkinsspatial** [comment]
@fredliporace 👍 I'm able to install directly from the branch and test.
