### ISSUE TITLE
Potential incompatibility with xml.etree and fsspec.

### ISSUE THREAD

**Issue by sharkinsspatial** [stactools-packages/amazonia-1#9]
**Describe the bug**
Running `create_item` on remote `fsspec` data fails with 
```
FileNotFoundError: [Errno 2] No such file or directory
```

**To reproduce**
Run `create_item` with 
`s3://amazonia-pds/AMAZONIA1/WFI/040/018/AMAZONIA_1_WFI_20230620_040_018_L4/AMAZONIA_1_WFI_20230620_040_018_L4_BAND2.xml`

**Additional context**
I believe this is due to an incompatibility with how `xml.etree` is interacting with `fsspec` but I have not tested in detail.
It might be worthwhile reviewing how the [stactools-landsat package](https://github.com/stactools-packages/landsat/blob/main/src/stactools/landsat/mtl_metadata.py) as they are successfully using an XML wrapper `stactools.core` for working with remote files.

**Comment by fredliporace** [comment]
Closed via #10
